language: perl
perl:
    - 5.10
    - 5.12
    - 5.14
    - 5.16
    - 5.18

before_install: cpanm Carton

install: carton install

script: ./run-tests

after_success: carton exec cover -report coveralls
