#!/bin/bash
set -e
rm -rf cover_db

if [[ $# -gt 0 ]]; then
    FILES=$*
else
    FILES=t/Ptero
fi

HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,local carton exec prove -vrl -I t $FILES
carton exec cover -report html
